### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by rodrigocanepa** [fayis672/epub_viewer#9]
I am trying to load this epub

https://firebasestorage.googleapis.com/v0/b/milo-12925.appspot.com/o/conexion.epub?alt=media&token=d372332d-1d84-45fd-8794-1d2003726a5d

and this as well:
https://firebasestorage.googleapis.com/v0/b/milo-12925.appspot.com/o/content.opf?alt=media&token=6cf378ea-6609-49aa-9664-8412253b4721

the first one is .epub and the second one is .opf as your example, but when I try to use it this error si showed in the terminal:
Access to XMLHttpRequest at 'https://firebasestorage.googleapis.com/v0/b/milo-12925.appspot.com/o/content.opf?alt=media' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.}

and the page goes to blank, thank you

**Comment by fayis672** [comment]
You need to change CORS policy of Firebase storage, [refer here ](https://firebase.google.com/docs/storage/web/download-files#cors_configuration). If you don't want any domain-based restrictions set `"origin": ["*"]`  otherwise set origin to localhost since Epub runs in a local server inside the APP.

**Comment by fayis672** [comment]
From version  `1.1.0 `  the EPUB loading has major changes, hence this issue is solved
